name: Java CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin .dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
      - name: Build, tag, and push image to Amazon ECR
        # env:
        #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #   ECR_REPOSITORY: kampdevecr
        #   IMAGE_TAG: springbootapplication
        run: |
          echo "ECR Registry: $ECR_REGISTRY/$ECR_REPOSITORY"
          docker build -t kampdevecr .
          docker tag kampdevecr:latest ${{ secrets.ECR_REPO_URL }}:springboot-latest
          docker push ${{ secrets.ECR_REPO_URL }}:springboot-latest
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Pull Image from ECR
        run: docker pull integrationninjas/springboot-example:latest
      - name: Delete old container
        run: docker rm -f springboot-example-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container integrationninjas/springboot-example
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_KAMP_EC2_IP }}
          username: ${{ secrets.AWS_KAMP_EC2_USER }}
          key: ${{ secrets.PRIVATE_KEY_PEM }}
          script: |
            docker run -d -p 8080:8080 --name springboot-example-container integrationninjas/springboot-example
